# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: vineetsalve0@gmail.com
author_name: Vineet
contract_name: subscription_contract
deployment_language: python
preset_name: production
project_name: Steemit-contracts

